package org.boyerfamily.euler;

/**
 * Project Euler, Problem 2:
 *   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 *   the first 10 terms will be:
 *
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 *   even-valued terms.
 *
 * Created by : aboyer (5/1/12 11:46 AM)
 */
public class Problem2 {
    public static void main(String[] args) {
        // This is still simple enough that brute force works just fine

        int sum = 2; // Start off with 2, since our loop already builds in the first two terms, one of which is even
        int first = 1;
        int second = 2;
        int result = 3;

        while (result < 4000000) {
            result = first+second;
            first = second;
            second = result;

            if (result%2==0)
                sum += result;
        }

        System.out.println("Sum of even Fibonacci numbers up to four million: "+sum);
    }
}
